In [31]:
import numpy as np 
import pandas as pd 

In [34]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

In [35]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [36]:
books = books.iloc[:,:5]

In [37]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [38]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [39]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [40]:
user_rating_count = ratings.groupby('User-ID').count().sort_values(by = 'ISBN', ascending = False)

In [41]:
user_rating_count.shape

(105283, 2)

In [42]:
user_rating_count = user_rating_count[user_rating_count['ISBN']>100]

In [43]:
user_rating_count.shape

(1825, 2)

In [44]:
book_rating_count = ratings.groupby('ISBN').count().sort_values(by = 'Book-Rating', ascending = False)

In [45]:
book_rating_count.head(10)

User-ID  Book-Rating
ISBN                            
0971880107     2502         2502
0316666343     1295         1295
0385504209      883          883
0060928336      732          732
0312195516      723          723
044023722X      647          647
0679781587      639          639
0142001740      615          615
067976402X      614          614
0671027360      586          586

In [46]:
book_rating_count = book_rating_count[book_rating_count['User-ID'] > 50]

In [47]:
ratings = ratings.merge(books, on = 'ISBN')

In [48]:
ratings.head()

User-ID        ISBN  Book-Rating            Book-Title Book-Author  \
0   276725  034545104X            0  Flesh Tones: A Novel  M. J. Rose   
1     2313  034545104X            5  Flesh Tones: A Novel  M. J. Rose   
2     6543  034545104X            0  Flesh Tones: A Novel  M. J. Rose   
3     8680  034545104X            5  Flesh Tones: A Novel  M. J. Rose   
4    10314  034545104X            9  Flesh Tones: A Novel  M. J. Rose   

  Year-Of-Publication         Publisher  
0                2002  Ballantine Books  
1                2002  Ballantine Books  
2                2002  Ballantine Books  
3                2002  Ballantine Books  
4                2002  Ballantine Books

In [49]:
ratings.shape

(1031136, 7)

In [50]:
ratings = ratings[ratings['User-ID'].isin(user_rating_count.index)]

In [51]:
ratings.shape

(604854, 7)

In [52]:
ratings = ratings[ratings['ISBN'].isin(book_rating_count.index)]

In [53]:
ratings.shape

(116873, 7)

In [54]:
ratings.head()

User-ID        ISBN  Book-Rating            Book-Title Book-Author  \
2      6543  034545104X            0  Flesh Tones: A Novel  M. J. Rose   
4     10314  034545104X            9  Flesh Tones: A Novel  M. J. Rose   
5     23768  034545104X            0  Flesh Tones: A Novel  M. J. Rose   
7     28523  034545104X            0  Flesh Tones: A Novel  M. J. Rose   
14    77480  034545104X            8  Flesh Tones: A Novel  M. J. Rose   

   Year-Of-Publication         Publisher  
2                 2002  Ballantine Books  
4                 2002  Ballantine Books  
5                 2002  Ballantine Books  
7                 2002  Ballantine Books  
14                2002  Ballantine Books

In [55]:
piv_table = ratings.pivot_table(columns = "User-ID", index = "ISBN", values = "Book-Rating")

In [56]:
piv_table.shape

(2101, 1793)

In [57]:
piv_table.iloc[:100, :100]

User-ID     254    507    882    1424   1435   1733   1903   2033   2110   \
ISBN                                                                        
000649840X    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
002026478X    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0020442203    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
002542730X    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0028604199    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
0061097659    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061097853    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061097861    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061098035    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061098361    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

User-ID     2276   ...  16161  16413  16488  16601  16634  16721  16795  \
ISBN               ...                                                    
000649840X    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
002026478X    NaN  ...    NaN    NaN    0.0    NaN    NaN    NaN    NaN   
0020442203    NaN  ...    NaN    NaN    NaN    NaN    9.0    NaN    NaN   
002542730X    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    0.0   
0028604199    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...  ...    ...    ...    ...    ...    ...    ...    ...   
0061097659    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061097853    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061097861    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
0061098035    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    0.0   
0061098361    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    0.0   

User-ID     16916  16943  16966  
ISBN                             
000649840X    NaN    NaN    NaN  
002026478X    NaN    NaN    NaN  
0020442203    NaN    NaN    NaN  
002542730X    NaN    NaN    NaN  
0028604199    NaN    NaN    NaN  
...           ...    ...    ...  
0061097659    NaN    NaN    NaN  
0061097853    NaN    NaN    NaN  
0061097861    NaN    NaN    NaN  
0061098035    NaN    NaN    NaN  
0061098361    NaN    NaN    NaN  

[100 rows x 100 columns]

In [58]:
piv_table = piv_table.fillna(0)

In [59]:
pd.DataFrame(piv_table).isnull().sum().sum()

0

In [60]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(piv_table)

NearestNeighbors(algorithm='brute')

In [61]:
ratings.sample(frac = 0.001)

User-ID        ISBN  Book-Rating  \
17760     68555  0061097101            0   
194471   174092  0413537900            8   
189539    16795  0385720106            9   
51913    275970  0385486804            0   
135891   230522  0312958129            0   
...         ...         ...          ...   
395273   208147  0515116068            0   
385667   244736  0515103292            7   
18530    246311  0380731851            8   
111726   173415  0446605239            0   
99265    216683  0743237188            0   

                                         Book-Title          Book-Author  \
17760                    The Saving Graces: A Novel     Patricia Gaffney   
194471  The Secret Diary of Adrian Mole Aged 13 3/4         Sue Townsend   
189539                           A Map of the World        Jane Hamilton   
51913                                 Into the Wild         Jon Krakauer   
135891                                  Coming Home    Rosamunde Pilcher   
...                                             ...                  ...   
395273                                Hidden Riches         Nora Roberts   
385667                            When Rabbit Howls         Truddi Chase   
18530                                  Mystic River        Dennis Lehane   
111726                                 The Notebook      Nicholas Sparks   
99265                Fall On Your Knees (Oprah #45)  Ann-Marie MacDonald   

       Year-Of-Publication               Publisher  
17760                 2000             HarperTorch  
194471                1982  Methuen Publishing Ltd  
189539                1999  Anchor Books/Doubleday  
51913                 1997                  Anchor  
135891                1996      St. Martin's Press  
...                    ...                     ...  
395273                2004              Jove Books  
385667                1990              Jove Books  
18530                 2002             HarperTorch  
111726                1998            Warner Books  
99265                 2002              Touchstone  

[117 rows x 7 columns]

In [62]:
piv_table[piv_table.index == '0618002227']

User-ID     254     507     882     1424    1435    1733    1903    2033    \
ISBN                                                                         
0618002227     8.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

User-ID     2110    2276    ...  276018  276463  276680  276925  277427  \
ISBN                        ...                                           
0618002227     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   

User-ID     277478  277639  278137  278188  278418  
ISBN                                                
0618002227     0.0     0.0     0.0     0.0     0.0  

[1 rows x 1793 columns]

In [63]:
test_book = piv_table[piv_table.index == '0618002227'].values

In [64]:
test_book

array([[8., 0., 0., ..., 0., 0., 0.]])

In [65]:
model.kneighbors(test_book)

(array([[ 0.        , 41.76122604, 41.78516483, 41.78516483, 41.86884283]]),
 array([[1626, 1001, 2098, 2088, 1299]], dtype=int64))

In [66]:
_, closest = model.kneighbors(test_book)

In [67]:
for i in closest[:5]:
    print(i)

[1626 1001 2098 2088 1299]


In [68]:
for i in closest[:5][0]:
    print(books[books['ISBN'] == piv_table.index[i]])

             ISBN                                         Book-Title  \
12763  0618002227  The Fellowship of the Ring (The Lord of the Ri...   

            Book-Author Year-Of-Publication                 Publisher  
12763  J. R. R. Tolkien                1999  Houghton Mifflin Company  
             ISBN                             Book-Title     Book-Author  \
18670  0440944597  The Chocolate War (Laurel Leaf Books)  ROBERT CORMIER   

      Year-Of-Publication    Publisher  
18670                1986  Laurel Leaf  
            ISBN               Book-Title      Book-Author  \
8838  3423202327  M�¶rder ohne Gesicht.  Henning Mankell   

     Year-Of-Publication Publisher  
8838                1999       Dtv  
            ISBN Book-Title   Book-Author Year-Of-Publication  \
3028  1844262553       Free  Paul Vincent                2003   

               Publisher  
3028  Upfront Publishing  
            ISBN    Book-Title   Book-Author Year-Of-Publication    Publisher
2227  04512088